
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Data:/Data
    env_file:
      - ./Backend/.env
    restart: always
    depends_on:
      - qdrant
    environment:
      QDRANT_HOST: "qdrant"
      QDRANT_PORT: "6333"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./Data/qdrant_data:/qdrant/storage
    restart: always


volumes:
  qdrant_data: